import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const products = [
    {
      nome: 'O Senhor dos Anéis',
      autor: 'J.R.R. Tolkien',
      price: 'R$ 80,00',
      img: '/assets/ex.jpg',
      genero: 'fantasia',
      createdAt: new Date(),
    },
    {
      nome: 'Harry Potter e a Pedra Filosofal',
      autor: 'J.K. Rowling',
      price: 'R$ 50,00',
      img: '/assets/ex.jpg',
      genero: 'fantasia',
      createdAt: new Date(),
    },
    {
      nome: 'O Hobbit',
      autor: 'J.R.R. Tolkien',
      price: 'R$ 45,00',
      img: '/assets/ex.jpg',
      genero: 'fantasia',
      createdAt: new Date(),
    },
    {
      nome: 'A Guerra dos Tronos',
      autor: 'George R.R. Martin',
      price: 'R$ 70,00',
      img: '/assets/ex.jpg',
      genero: 'fantasia',
      createdAt: new Date(),
    },
    {
      nome: 'O Nome do Vento',
      autor: 'Patrick Rothfuss',
      price: 'R$ 55,00',
      img: '/assets/ex.jpg',
      genero: 'fantasia',
      createdAt: new Date(),
    },
    {
      nome: 'Mistborn: O Império Final',
      autor: 'Brandon Sanderson',
      price: 'R$ 60,00',
      img: '/assets/ex.jpg',
      genero: 'fantasia',
      createdAt: new Date(),
    },
    {
      nome: '1984',
      autor: 'George Orwell',
      price: 'R$ 35,00',
      img: '/assets/ex.jpg',
      genero: 'ficção científica',
      createdAt: new Date(),
    },
    {
      nome: 'Admirável Mundo Novo',
      autor: 'Aldous Huxley',
      price: 'R$ 40,00',
      img: '/assets/ex.jpg',
      genero: 'ficção científica',
      createdAt: new Date(),
    },
    {
      nome: 'Fahrenheit 451',
      autor: 'Ray Bradbury',
      price: 'R$ 30,00',
      img: '/assets/ex.jpg',
      genero: 'ficção científica',
      createdAt: new Date(),
    },
    {
      nome: 'Duna',
      autor: 'Frank Herbert',
      price: 'R$ 75,00',
      img: '/assets/ex.jpg',
      genero: 'ficção científica',
      createdAt: new Date(),
    },
    {
      nome: 'Neuromancer',
      autor: 'William Gibson',
      price: 'R$ 50,00',
      img: '/assets/ex.jpg',
      genero: 'ficção científica',
      createdAt: new Date(),
    },
    {
      nome: 'Fundação',
      autor: 'Isaac Asimov',
      price: 'R$ 65,00',
      img: '/assets/ex.jpg',
      genero: 'ficção científica',
      createdAt: new Date(),
    },
    {
      nome: 'Orgulho e Preconceito',
      autor: 'Jane Austen',
      price: 'R$ 45,00',
      img: '/assets/ex.jpg',
      genero: 'romance',
      createdAt: new Date(),
    },
    {
      nome: 'Jane Eyre',
      autor: 'Charlotte Brontë',
      price: 'R$ 50,00',
      img: '/assets/ex.jpg',
      genero: 'romance',
      createdAt: new Date(),
    },
    {
      nome: 'O Morro dos Ventos Uivantes',
      autor: 'Emily Brontë',
      price: 'R$ 55,00',
      img: '/assets/ex.jpg',
      genero: 'romance',
      createdAt: new Date(),
    },
    {
      nome: 'Anna Karenina',
      autor: 'Leo Tolstoy',
      price: 'R$ 60,00',
      img: '/assets/ex.jpg',
      genero: 'romance',
      createdAt: new Date(),
    },
    {
      nome: 'Dom Casmurro',
      autor: 'Machado de Assis',
      price: 'R$ 35,00',
      img: '/assets/ex.jpg',
      genero: 'romance',
      createdAt: new Date(),
    },
    {
      nome: 'O Grande Gatsby',
      autor: 'F. Scott Fitzgerald',
      price: 'R$ 40,00',
      img: '/assets/ex.jpg',
      genero: 'romance',
      createdAt: new Date(),
    },
    {
      nome: 'Sherlock Holmes: Um Estudo em Vermelho',
      autor: 'Arthur Conan Doyle',
      price: 'R$ 30,00',
      img: '/assets/ex.jpg',
      genero: 'mistério',
      createdAt: new Date(),
    },
    {
      nome: 'Assassinato no Expresso do Oriente',
      autor: 'Agatha Christie',
      price: 'R$ 35,00',
      img: '/assets/ex.jpg',
      genero: 'mistério',
      createdAt: new Date(),
    },
    {
      nome: 'O Código Da Vinci',
      autor: 'Dan Brown',
      price: 'R$ 45,00',
      img: '/assets/ex.jpg',
      genero: 'mistério',
      createdAt: new Date(),
    },
    {
      nome: 'O Silêncio dos Inocentes',
      autor: 'Thomas Harris',
      price: 'R$ 50,00',
      img: '/assets/ex.jpg',
      genero: 'mistério',
      createdAt: new Date(),
    },
    {
      nome: 'O Nome da Rosa',
      autor: 'Umberto Eco',
      price: 'R$ 55,00',
      img: '/assets/ex.jpg',
      genero: 'mistério',
      createdAt: new Date(),
    },
    {
      nome: 'Rebecca',
      autor: 'Daphne du Maurier',
      price: 'R$ 40,00',
      img: '/assets/ex.jpg',
      genero: 'mistério',
      createdAt: new Date(),
    },
    {
      nome: 'O Processo',
      autor: 'Franz Kafka',
      price: 'R$ 40,00',
      img: '/assets/ex.jpg',
      genero: 'drama',
      createdAt: new Date(),
    },
    {
      nome: 'Crime e Castigo',
      autor: 'Fyodor Dostoevsky',
      price: 'R$ 60,00',
      img: '/assets/ex.jpg',
      genero: 'drama',
      createdAt: new Date(),
    },
    {
      nome: 'A Metamorfose',
      autor: 'Franz Kafka',
      price: 'R$ 30,00',
      img: '/assets/ex.jpg',
      genero: 'drama',
      createdAt: new Date(),
    },
    {
      nome: 'Os Miseráveis',
      autor: 'Victor Hugo',
      price: 'R$ 80,00',
      img: '/assets/ex.jpg',
      genero: 'drama',
      createdAt: new Date(),
    },
    {
      nome: 'Cem Anos de Solidão',
      autor: 'Gabriel García Márquez',
      price: 'R$ 70,00',
      img: '/assets/ex.jpg',
      genero: 'drama',
      createdAt: new Date(),
    },
    {
      nome: 'O Estrangeiro',
      autor: 'Albert Camus',
      price: 'R$ 45,00',
      img: '/assets/ex.jpg',
      genero: 'drama',
      createdAt: new Date(),
    },
    {
      nome: 'O Poderoso Chefão',
      autor: 'Mario Puzo',
      price: 'R$ 50,00',
      img: '/assets/ex.jpg',
      genero: 'ação',
      createdAt: new Date(),
    },
    {
      nome: 'Jogos Vorazes',
      autor: 'Suzanne Collins',
      price: 'R$ 40,00',
      img: '/assets/ex.jpg',
      genero: 'ação',
      createdAt: new Date(),
    },
    {
      nome: 'Maze Runner: Correr ou Morrer',
      autor: 'James Dashner',
      price: 'R$ 35,00',
      img: '/assets/ex.jpg',
      genero: 'ação',
      createdAt: new Date(),
    },
    {
      nome: 'O Último dos Moicanos',
      autor: 'James Fenimore Cooper',
      price: 'R$ 55,00',
      img: '/assets/ex.jpg',
      genero: 'ação',
      createdAt: new Date(),
    },
    {
      nome: 'O Conde de Monte Cristo',
      autor: 'Alexandre Dumas',
      price: 'R$ 65,00',
      img: '/assets/ex.jpg',
      genero: 'ação',
      createdAt: new Date(),
    },
    {
      nome: 'A Ilha do Tesouro',
      autor: 'Robert Louis Stevenson',
      price: 'R$ 30,00',
      img: '/assets/ex.jpg',
      genero: 'ação',
      createdAt: new Date(),
    },
    {
      nome: 'Moby Dick',
      autor: 'Herman Melville',
      price: 'R$ 70,00',
      img: '/assets/ex.jpg',
      genero: 'ação',
      createdAt: new Date(),
    },
    {
      nome: '20.000 Léguas Submarinas',
      autor: 'Jules Verne',
      price: 'R$ 45,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'Robinson Crusoé',
      autor: 'Daniel Defoe',
      price: 'R$ 50,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'Viagem ao Centro da Terra',
      autor: 'Jules Verne',
      price: 'R$ 40,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'O Corsário Negro',
      autor: 'Emilio Salgari',
      price: 'R$ 35,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'As Aventuras de Tom Sawyer',
      autor: 'Mark Twain',
      price: 'R$ 30,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'O Príncipe e o Mendigo',
      autor: 'Mark Twain',
      price: 'R$ 35,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'A Volta ao Mundo em 80 Dias',
      autor: 'Jules Verne',
      price: 'R$ 40,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'O Conde de Monte Cristo',
      autor: 'Alexandre Dumas',
      price: 'R$ 65,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'A Ilha Misteriosa',
      autor: 'Jules Verne',
      price: 'R$ 50,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'Aventuras de Huckleberry Finn',
      autor: 'Mark Twain',
      price: 'R$ 45,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'O Último Reino',
      autor: 'Bernard Cornwell',
      price: 'R$ 60,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'Ivanhoé',
      autor: 'Walter Scott',
      price: 'R$ 55,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'Capitães da Areia',
      autor: 'Jorge Amado',
      price: 'R$ 30,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },
    {
      nome: 'O Senhor das Moscas',
      autor: 'William Golding',
      price: 'R$ 40,00',
      img: '/assets/ex.jpg',
      genero: 'aventura',
      createdAt: new Date(),
    },  
  ];

  for (const product of products) {
    await prisma.product.create({
      data: product,
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
